<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Surat_model extends CI_Model
{

    public $table = 'surat_keterangan';
    public $id = 'surat_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        //$this->db->order_by($this->id, $this->order);
        //return $this->db->get($this->table)->result();

        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->join('prodi', 'prodi.prodi_id = '.$this->table.'.prodi_id', 'left');
        $this->db->join('kategori', 'kategori.kategori_id = '.$this->table.'.kategori_id', 'left');
        $this->db->get()->result();

    }    

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->join('prodi', 'prodi.prodi_id = '.$this->table.'.prodi_id', 'left');
        $this->db->join('kategori', 'kategori.kategori_id = '.$this->table.'.kategori_id', 'left');
        $this->db->where($this->id, $id);
        return $this->db->get()->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('surat_id', $q);
        $this->db->or_like('surat_nama', $q);
        $this->db->or_like('surat_tmpt_lahir', $q);
        $this->db->or_like('surat_nim', $q);
        $this->db->or_like('surat_alamat', $q);
        $this->db->or_like('prodi_id', $q);
        $this->db->or_like('kategori_id', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by('status', 'ASC');
        $this->db->like('surat_nama', $q);
        $this->db->or_like('surat_tmpt_lahir', $q);
        $this->db->or_like('surat_nim', $q);
        $this->db->or_like('surat_alamat', $q);
        $this->db->or_like('prodi_name', $q);
        $this->db->or_like('kategori_name', $q);
        $this->db->limit($limit, $start);
        $this->db->select('status,surat_id, surat_nama, surat_tmpt_lahir, surat_tgl_lahir, surat_nim, semester, surat_alamat, t2.prodi_name as prodi_name, t3.kategori_name as kategori_name');
        //$this->db->select('*');
        $this->db->from('surat_keterangan AS t1');
        $this->db->join('prodi AS t2', 't1.prodi_id = t2.prodi_id');
        $this->db->join('kategori as t3', 't1.kategori_id = t3.kategori_id');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }    

    // update data
    function konfirmasi($id, $data)
    {
        $this->db->where($this->id, $id);
        // $this->db->set('status',array('' => , ););
        $this->db->update($this->table, $data);
    }
    
    // update data
    function tolak($id, $data)
    {
        $this->db->where($this->id, $id);
        // $this->db->set('status',array('' => , ););
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Surat_model.php */
/* Location: ./application/models/Surat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-10 18:41:49 */
/* http://harviacode.com */